### ISSUE TITLE
hi! could you share the code for event encoding into 6 channels as described in the paper?

### ISSUE THREAD

**Issue by ShristiDasBiswas** [CooKySch/DL_EvSegNet#1]

**Comment by CooKySch** [comment]
It's stated in train-eager.py, starting from line 182 and further defined in the model (line 201). However, this is not the original repository of the paper, but just a reconstruction done for a project by a few students who are currently on holidays. The original repository can be found [here](https://github.com/Shathe/Ev-SegNet). Essentially it is the same code but our repository works with python3 and tensorflow2, but we are not planning any further maintenance.
