### ISSUE TITLE
It seems that the link for dataset is broken

### ISSUE THREAD

**Issue by dianzizs** [CooKySch/DL_EvSegNet#2]
The download link provided for the groundtruth of dataset ddd17 is no longer working.  I was wondering if you still have a backup of this dataset? Can you update the downloaded link？

**Comment by CooKySch** [comment]
Good news, I've got it for you: https://drive.google.com/file/d/1oPPXbaQC9cYis5FoTLmWF-YbIL7X8rm0/view?usp=drive_link

**Comment by dianzizs** [comment]
Thank you so much, that helps a lot
